import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Type } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

const app = express();
const PORT = 3000;

app.use(express.json({ limit: '10mb' }));

// Helper to get the GoogleGenAI instance lazily
let aiInstance: GoogleGenAI | null = null;
function getAI(): GoogleGenAI {
  if (!aiInstance) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error("GEMINI_API_KEY environment variable is not defined. Please add it to your environment secrets.");
    }
    aiInstance = new GoogleGenAI({
      apiKey: apiKey,
      httpOptions: {
        headers: {
          'User-Agent': 'aistudio-build',
        }
      }
    });
  }
  return aiInstance;
}

// Ensure error handling doesn't leak internals as HTML
app.use((err: any, req: express.Request, res: express.Response, next: express.NextFunction) => {
  console.error("Unhandled express error:", err);
  if (res.headersSent) {
    return next(err);
  }
  res.status(500).json({ error: err.message || "An unexpected server error occurred." });
});

// Endpoint: Clinical symptom triage
app.post("/api/assess-symptoms", async (req, res) => {
  try {
    const { name, age, symptoms } = req.body;
    if (!name || !symptoms) {
      return res.status(400).json({ error: "Missing patient name or symptom description." });
    }

    const ai = getAI();
    const prompt = `Please perform a clinical triage analysis for a patient, selecting an Emergency Severity Index (ESI) from 1 to 5 based on standard medical guidelines:
1 - Immediate / Resuscitation (most critical, e.g., cardiac arrest, respiratory failure, severe trauma)
2 - Emergent / High risk (severe pain, chest pressure, stroke signs, heavy bleeding, active mental status change)
3 - Urgent / Stable (stable but requires multiple medical resources, e.g., fractured limb with good pulse, mild asthma flare-up, high fever with severe local symptoms)
4 - Semi-urgent / Less urgent (stable, requires one resource, e.g., simple laceration needing sutures, ankle sprain needing x-ray, earache)
5 - Non-urgent / Least urgent (stable, requires no resources beyond diagnostic test or advice/rx, e.g., simple rash, cold symptoms, prescription refill)

Patient Name: ${name}
Age: ${age || 'Unknown'}
Symptom Description: "${symptoms}"`;

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: prompt,
      config: {
        systemInstruction: "You are an expert emergency medical triage advisor. Assess the Emergency Severity Index (ESI) of the described symptoms accurately according to standard clinical procedures. Be realistic, safety-focused, and compassionate. Always provide patient-friendly, reassuring, and clear explanations.",
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            esi: {
              type: Type.INTEGER,
              description: "Assessed Emergency Severity Index level, an integer from 1 to 5."
            },
            esiName: {
              type: Type.STRING,
              description: "E.g., 'Level 3: Urgent', 'Level 2: Emergent', or 'Level 4: Semi-Urgent'."
            },
            explanation: {
              type: Type.STRING,
              description: "A comforting, reassuring, patient-friendly explanation of why they are assigned this ESI in a single simple sentence."
            },
            nextSteps: {
              type: Type.STRING,
              description: "What the patient should expect next upon arrival or wait-room setup, such as vitals check or fast-track care."
            }
          },
          required: ["esi", "esiName", "explanation", "nextSteps"]
        }
      }
    });

    if (!response.text) {
      throw new Error("No response content generated by AI.");
    }

    const result = JSON.parse(response.text.trim());
    return res.json(result);
  } catch (error: any) {
    console.error("Error in ESI assessment:", error);
    res.status(500).json({ error: error.message || "Failed to perform triage assessment." });
  }
});

// Endpoint: Message summary to the contact upon registration
app.post("/api/chat-open", async (req, res) => {
  try {
    const { name, esi, esiName, explanation, nextSteps, waitTime, contactName, relationship } = req.body;
    if (!name) {
      return res.status(400).json({ error: "Missing required fields." });
    }

    const ai = getAI();
    const prompt = `Generate a warm, professional, and clear introductory SMS update sent from Helping Hand Urgent Care to ${contactName} (the patient's emergency contact, relationship: ${relationship}).
The patient is ${name}.
Triage details:
- Clinical Assessment: ${esiName} (ESI level ${esi})
- Assessment reason: ${explanation}
- Next steps: ${nextSteps}
- Estimated wait time to see a physician: ${waitTime} minutes

Provide a warm and highly reassuring message summarizing that ${name} checked in safely, how they are being cared for (layperson wording), what's happening next, and the current projected timing. Make sure it sounds like a real professional and caring SMS notification, reassuring the contact that their loved one is in great hands. Keep it concise, under 120 words total. Do not use complex medical jargon or system markers.`;

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: prompt,
      config: {
        systemInstruction: "You are a warm, reassuring patient advocate and clinical triage assistant at Helping Hand Urgent Care clinic. Your goal is to provide calming, clear updates to families/contacts."
      }
    });

    const smsText = response.text || "Hello, this is Helping Hand. Your emergency contact is checked in and in stable care. We will keep you updated.";
    return res.json({ text: smsText.trim() });
  } catch (error: any) {
    console.error("Error generating open chat message:", error);
    res.status(500).json({ error: error.message || "Failed to generate opening update." });
  }
});

// Endpoint: Reply to contact message
app.post("/api/chat-reply", async (req, res) => {
  try {
    const { chatHistory, patientName, esi, symptoms, currentPosition, estWaitTime, newMessage, contactName } = req.body;
    if (!patientName || !newMessage) {
      return res.status(400).json({ error: "Missing chat data or patient info." });
    }

    const ai = getAI();
    
    const prompt = `You are the Helping Hand AI Assistant answering a message from ${contactName}, the emergency contact of ${patientName}.
Patient's symptoms: "${symptoms}"
Patient's Triaged ESI Level: ${esi}
Current Status of ${patientName}:
- Position in waiting room queue: #${currentPosition} in line
- Estimated wait time left: ${estWaitTime} minutes

Here is the chat history:
${(chatHistory || []).map((m: any) => `${m.sender === 'ai' ? 'Helping Hand AI' : contactName}: ${m.text}`).join('\n')}

New message from ${contactName}: "${newMessage}"

Write a brief, polite, compassionate, and highly reassuring reply. 
- Address their specific questions or concerns.
- Inform them of the patient's queue position (#${currentPosition}) or estimated wait (${estWaitTime} minutes) dynamically and gently.
- Explicitly emphasize that our clinical team is monitoring the wait-room constantly and will step in immediately if they notice any change in symptoms.
- Keep the response clean and suitable for SMS (under 100 words).`;

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: prompt,
      config: {
        systemInstruction: "You are a warm, reassuring, clinical communications assistant. You reply to emergency contact text messages for registered patients, explaining details in humble, human terms. Never provide absolute medical diagnoses but remind them that professional nurses/doctors are supervising everyone directly."
      }
    });

    const replyText = response.text || "Thank you for reaching out. We are continuing to monitor their status and will provide updates as soon as possible.";
    return res.json({ text: replyText.trim() });
  } catch (error: any) {
    console.error("Error generating chat reply:", error);
    res.status(500).json({ error: error.message || "Failed to generate chat reply." });
  }
});

// Start Express and bundle Vite
async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on port ${PORT}`);
  });
}

startServer();
